name: "Setup Node.js environment"
description: "Sets up Node.js and installs dependencies"

runs:
    using: "composite"
    steps:
        -   name: Setup Node.js environment
            uses: actions/setup-node@v4
            with:
                node-version: "lts/*"
                cache: "npm"
                cache-dependency-path: "**/package-lock.json"

        -   name: Install Dependencies
            run: npm ci
            shell: bash
