apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: backend-ingress
    namespace: exsys-staging
    annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
    ingressClassName: nginx
    tls:
        -   hosts:
                - staging.kantine.nyskivehus.dk
            secretName: backend-tls
    rules:
        -   host: staging.kantine.nyskivehus.dk
            http:
                paths:
                    # API Path
                    -   path: /api/
                        pathType: Prefix
                        backend:
                            service:
                                name: backend-service
                                port:
                                    number: 80
