name: "Push Docker Image"
description: "Builds and pushes Docker image to Docker Hub"

inputs:
    username:
        description: "Docker Hub username"
        required: true
    password:
        description: "Docker Hub password"
        required: true
    tag:
        description: "Docker image tag"
        required: true

runs:
    using: "composite"
    steps:
        -   name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

        -   name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ inputs.username }}
                password: ${{ inputs.password }}

        -   name: Build and push Docker image
            run: |
                docker buildx create --use
                docker buildx build --file Dockerfile --platform linux/arm64,linux/amd64 --push --tag ${{ inputs.username }}/exsys-backend:${{ inputs.tag }} .
            shell: bash
