apiVersion: v1
kind: Service
metadata:
    name: backend-service
    namespace: exsys-prod
spec:
    type: ClusterIP
    selector:
        app: backend-deployment
    ports:
        - protocol: TCP
          port: 80
          targetPort: 5000
